# Generated by Django 4.1.7 on 2023-03-08 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_reservation', '0005_alter_bus_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='bus_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
