# Generated by Django 4.1.7 on 2023-03-03 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bus_reservation', '0003_alter_ticket_bus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus_reservation.bus'),
        ),
    ]
