# Generated by Django 4.1.7 on 2023-03-08 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_reservation', '0004_alter_ticket_bus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
