# Generated by Django 4.1.7 on 2023-03-14 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('air', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='arrival_airport',
            new_name='destination',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='departure_airport',
            new_name='source',
        ),
    ]
