# Generated by Django 4.1.7 on 2023-03-14 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air', '0002_rename_arrival_airport_flight_destination_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
